### ISSUE TITLE
Single-line block references for blocks with deadline/logbook 

### ISSUE THREAD

**Issue by abhilesh** [stdword/logseq-bujo-theme#1]
The block references with a `Deadline` or a `Logbook` field spread across multiple lines with the last line being only used for completing the highlighting for the block as seen in the attached screenshot

<img width="898" alt="Screenshot 2023-02-23 at 13 16 28" src="https://user-images.githubusercontent.com/2447878/220917826-a46d0d06-376e-4666-a60c-1b4ece89a7ac.png">

**Comment by stdword** [comment]
@abhilesh finally fixed! 🙌
https://github.com/stdword/logseq-bujo-theme/releases/tag/0.4.0
