### ISSUE TITLE
References to PDF area highlights  

### ISSUE THREAD

**Issue by Dunrar** [stdword/logseq-bujo-theme#3]
References to PDF area highlights add distracting bars to the top and bottom.

This is how it looks using bujo-theme Sepia:
![image](https://github.com/stdword/logseq-bujo-theme/assets/23218622/ab7ef75c-e1d5-4c92-835d-39f7b83cf182)

It looks like it is supposed to using the White theme:
![image](https://github.com/stdword/logseq-bujo-theme/assets/23218622/16c492f8-218d-4d3c-94d4-af3ec30944b3)

**Comment by abhilesh** [comment]
I have the same issue while using the coffee theme.
<img width="882" alt="Screenshot 2023-09-13 at 12 23 50" src="https://github.com/stdword/logseq-bujo-theme/assets/2447878/cf214062-a254-41a1-9af7-77619b4909bc">

Maybe it's similar to https://github.com/stdword/logseq-bujo-theme/issues/1?

**Comment by stdword** [comment]
> Maybe it's similar to https://github.com/stdword/logseq-bujo-theme/issues/1?

It is very similar, but different.
Will fix this issue. But need some time to get to the work
