### ISSUE TITLE
support mobile device

### ISSUE THREAD

**Issue by ThreeIce** [stdword/logseq-bujo-theme#4]

**Comment by stdword** [comment]
@ThreeIce You can use any selected theme on mobile device via Logseq's `logseq/custom.css` file.

## Steps
1. Copy whole content of `src/base.css` to the bottom of `custom.css`
2. Copy whole content of *selected* theme (e.g. `src/dark-coffee.css`) to the bottom of `custom.css`
3. Remove line `@import './base.css';`

This should help. BUT I didn't test it.
