### ISSUE TITLE
Property icons not rendered

### ISSUE THREAD

**Issue by abhilesh** [stdword/logseq-bujo-theme#6]
I am using v0.8.0 of the theme and the property icons aren't rendering for me. My custom.css is empty so there shouldn't be anything interfering with the theming. Do I need to have tabler fonts installed locally for the icons to be rendered?

<img width="926" alt="Screenshot 2023-09-13 at 11 43 51" src="https://github.com/stdword/logseq-bujo-theme/assets/2447878/c3888f35-5479-4e15-a550-404074094652">

**Comment by stdword** [comment]
Well, this is interesting. No, you don't need to install any additional plugins / fonts. It should work.
Could you try to disable some plugins? It is just an assumption, but one of them could be the reason.

**Comment by abhilesh** [comment]
I disabled all the plugins and uninstalled and reinstalled the theme as well but the issue persists

**Comment by stdword** [comment]
@abhilesh try this code as `custom.css` to ensure it works for you:
```
.page-property-key[data-ref|="date"]::before        { content: "\ea53" }
```

icon for `date` property should appear
if not, try this one:
```
.page-property-key[data-ref|="date"]::before        { content: "\ea53" !important }
```

**Comment by abhilesh** [comment]
The above snippets did not work for me, but I figured out what the issue was with my setup.
I had disabled "property pages" in my `config.edn`, I reverted it with `:property-pages/enabled? true` and now the property icons are rendered. 

Seems like Logseq requires property pages for the icons to be set. Thanks a lot!

**Comment by stdword** [comment]
Yes! I've forgot about it)
🔥
