### ISSUE TITLE
Question: Delete or Change Reference Background Color

### ISSUE THREAD

**Issue by RainSharky** [stdword/logseq-bujo-theme#9]
Is there a way to not have the background color or change it when copying a reference to a block

Example:

![image](https://github.com/stdword/logseq-bujo-theme/assets/125542081/73a97242-5d25-426f-8fff-1e2e2722f039)

**Comment by stdword** [comment]
Hello!
It seems you are using `Awesome Content` plugin. Note, the theme was designed without taking it into account and originally task looks different:
<img width="173" alt="CleanShot 2023-12-14 at 15 21 02@2x" src="https://github.com/stdword/logseq-bujo-theme/assets/1984175/e85267bf-0f3d-41d9-b76d-4a411d5cd5b0">

There is a way to change any style in Logseq with `custom.css`. But the appropriate CSS code should be developed by some one. You could ask for help in Logseq _discord community_ or at the forum: https://discuss.logseq.com.

**Comment by RainSharky** [comment]
Thank you very much! 👍 I will reach out in the forum
